language: php
php:
  - '7.0'
services:
  - mysql
install:
  - cp config.sample.php config.php
  - sed -i '' "s/'password'/''/g" tests/acceptance.suite.yml
  - composer install
  - mysql -e 'create database ppma1;'
  - php -S localhost:8080 -t ./public/ &
script:
  - vendor/bin/codecept run --debug
